### ISSUE TITLE
MVPレビュー

### ISSUE THREAD

**Issue by kerochelo** [murai-misaki/theGrimReaper_timer#59]
@murai-misaki 
お疲れ様です！
下記の観点でレビューを行っております。

1. READMEから課題解決する実装がされているか&動いている
2. 静的コードチェックが入っている
3. 就活において十分な技術力を示せる機能を実装しているか
4. UIでユーザーが迷わないような導線を作れているか・ユーザーが使いたくなるようなサービス設計ができているか

## READMEから課題解決する実装がされているか&動いている
READMEのマークダウンが崩れているので修正しておきましょう。
MVPとしてしっかりと課題解決の機能が実装できていますね、これから残りの実装を進めていただければ大丈夫です！
またまだ未実装の機能などに関してはREADMEの項目にも「実装中」などの文言を入れておくと見るときにわかりやすくなるので追記しておきましょう。

## 静的コードチェックが入っている
rubocopを導入してコードの見た目を整えておきましょう。

## 就活において十分な技術力を示せる機能を実装しているか
基本的にとてもいい感じにまとまっており、技術を活用して使いやすさや機能を実装していますね。下記に気になる点を記載するのでissue化して修正しておきましょう。
- Railsでjsonでレスポンスを作成している部分はシリアライズしておきましょう。（jsonapi-serializer：https://github.com/jsonapi-serializer/jsonapi-serializer）
- one_day_times_controllerのindexアクションのレスポンスの配列を作成するロジックはprivateメソッドなどに切り出しておきましょう。
- ActionCableでリアルタイムチャット機能など実装もありですが、フロントでvueを使っているのでちょっと実装が難しいかもしれないですので、優先度は下げてOKです。
- front側のsrc/onedaytimeのディレクトリはちょっと浮いているので、commonなどのディレクトリにしてその中でjsのファイルを管理するといいですね。
- 現在issueに残っている機能実装を中心に進めていきましょう。

##  UIでユーザーが迷わないような導線を作れているか・ユーザーが使いたくなるようなサービス設計ができているか
導線やUIは基本的に問題なさそうですね、完成度が高いです！
ブラウザの横幅によって、ログインやサインアップの部分が見切れたりするのでその部分の調整をしておきましょう。

こちらの内容を確認してそれぞれのタスクをissueに書き出したら、こちらのissueはcloseしていただいて大丈夫です。

**Comment by murai-misaki** [comment]
@kerochelo 
MVPレビューいただき、ありがとうございます！！
修正点をissue化したので、コードの改善に取り組んでいきます！

一点質問なのですが、以下のどの機能実装まで完了すれば本リリースして就活に入っても問題ないでしょうか。
本リリースまでに追加する機能の数によって本リリースまでの期間が変わると思うので、本リリースまでの計画を立てる参考にさせていただきたいのと、また面談でCTさんから「就活中も開発を続けるから本リリースまでにアプリを完成させる必要はない」と伺ったので、どの機能まで追加してから本リリースしたら良いか迷っている為、アドバイスいただければ幸いです。


以下の順で、機能を実装しようと考えております。
1. 1時間座り続けたことで縮んだ寿命の合計時間を知れる機能(twitterシェア機能つき)
2. ActionCableでリアルタイムチャット機能 (※ ActionCableを使用したWebSocket通信はVue.jsとRails APIのキャッチアップ時に一緒に勉強したので、恐らく実装出来ます！)
3. 利用規約・プライバシーポリシー
4. パスワードリセット機能
5. プロフィール編集・パスワード更新機能
6. アカウント削除機能
7. レスポンジブデザイン

**Comment by kerochelo** [comment]
@murai-misaki 
本リリースまでで考慮すると下記の4つで大丈夫かなと思います、こちらができたら就活をメインで進めていきましょう！
- 1時間座り続けたことで縮んだ寿命の合計時間を知れる機能(twitterシェア機能つき)
- 利用規約・プライバシーポリシー
- パスワードリセット機能
- プロフィール編集・パスワード更新機能


残りについては就活しながら実装してもらうで構わないです！下記の優先順で進めていきましょう！
- ActionCableでリアルタイムチャット機能 (※ ActionCableを使用したWebSocket通信はVue.jsとRails APIのキャッチアップ時に一緒に勉強したので、恐らく実装出来ます！)
- レスポンジブデザイン
- アカウント削除機能
レスポンジブデザイン

**Comment by murai-misaki** [comment]
@kerochelo 
ご回答いただき、誠にありがとうございます！！
かしこまりました！本リリースに向けて引き続き開発頑張ります！！

**Comment by murai-misaki** [comment]
@kerochelo 
度々のご連絡失礼します。
jsonapi-serializerで検索して、jsonapi-serializerのgithubページを表示することができました。
[jsonapi-serializer](https://github.com/jsonapi-serializer/jsonapi-serializer)
お手数おかけしてしまい申し訳ございません。
今後は確認をしっかり行ってから、ご質問するように以後気をつけます。🙇💦
